Insert Into motivo_retiro(Motivo) Values('N/A'), ('Renuncia Voluntaria')
, ('Terminación Contrato por Periodo de Prueba')
, ('Terminación Contrato Fijo')
, ('Terminación Contrato Sin justa Causa')
, ('Abandono de Trabajo')